name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        rails:
          - "8.0"
          - "8.1"
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Run tests
        run: bin/rails test

  test-ruby-4:
    runs-on: ubuntu-latest
    name: Ruby 4.0.0-preview3 / Rails 8.1
    env:
      RAILS_VERSION: "8.1"
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.0-preview3"
          bundler-cache: true

      - name: Run tests
        run: bin/rails test
